import type { ThreadState } from "../types";
import { PREFILL_TEMPLATE_REGEX } from "../lib/clinic-link";

// Negative lookahead `(?![a-z0-9-])` rejects a trailing hyphen or extra slug char,
// so `clinic_acme-` and `clinic_acme- hello` are not considered matches.
const TOKEN_RE = /^clinic_([a-z0-9](?:[a-z0-9-]{0,38}[a-z0-9])?)(?![a-z0-9-])\s*/i;

export type DeepLinkParse =
  | { kind: "none" }
  | { kind: "match"; slug: string; residual: string };

export function parseDeepLinkToken(text: string): DeepLinkParse {
  if (!text) return { kind: "none" };
  const m = text.match(TOKEN_RE);
  if (!m) return { kind: "none" };
  return {
    kind: "match",
    slug: m[1].toLowerCase(),
    residual: text.slice(m[0].length).trim(),
  };
}

export type DeepLinkClinic = { id: string; name: string };

/**
 * Mutates state for a deep-link arrival.
 * - Same clinic re-tap: idempotent, no wipe (preserves any in-progress booking).
 * - Different / no current clinic: wipes booking-scoped fields, sets activeClinicId.
 * - Identity-scoped fields (userId, patients, activePatientId, verified, language, phone) are preserved.
 */
export function applyDeepLink(state: ThreadState, clinic: DeepLinkClinic): void {
  if (state.activeClinicId === clinic.id) return;

  state.activeClinicId = clinic.id;
  state.activeServiceId = undefined;
  state.activeMethodId = undefined;
  state.activeDoctorId = undefined;
  state.lastSearchQuery = undefined;
  state.clinicOptions = [];
  state.serviceOptions = [];
  state.doctorOptions = [];
}

export type FriendlyPrefillParse =
  | { kind: "none" }
  | { kind: "match"; clinicName: string; residual: string };

/**
 * Recognises the prefill template generated by /c/[slug] (see src/lib/clinic-link.ts).
 * Distinct from parseDeepLinkToken — that handles the legacy `clinic_<slug>` token
 * and stays in place for backward compat with any links already in the wild.
 *
 * Residual is always empty for now (the template captures the entire message),
 * but the field is kept symmetric with DeepLinkParse so the call sites compose.
 */
export function parseFriendlyPrefill(text: string): FriendlyPrefillParse {
  if (!text) return { kind: "none" };
  const m = text.match(PREFILL_TEMPLATE_REGEX);
  if (!m) return { kind: "none" };
  return { kind: "match", clinicName: m[1].trim(), residual: "" };
}
